### ISSUE TITLE
ModuleNotFoundError("No module named 'src.models.components.uedm'")  Where can I find the uedm file, please?

### ISSUE THREAD

**Issue by bishr-omer** [XavierJiezou/Pansharpening#1]
Traceback (most recent call last):
  File "/home/bishr/.local/lib/python3.10/site-packages/hydra/_internal/utils.py", line 650, in _locate
    obj = import_module(mod)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'src.models.components.uedm'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/bishr/.local/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 134, in _resolve_target
    target = _locate(target)
  File "/home/bishr/.local/lib/python3.10/site-packages/hydra/_internal/utils.py", line 653, in _locate
    raise ImportError(
ImportError: Error loading 'src.models.components.uedm.UEDM':
ModuleNotFoundError("No module named 'src.models.components.uedm'")
Are you sure that 'uedm' is importable from module 'src.models.components'?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/bishr/Pansharpening/src/utils/utils.py", line 68, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "/home/bishr/Pansharpening/src/train.py", line 63, in train
    model: LightningModule = hydra.utils.instantiate(cfg.model)
  File "/home/bishr/.local/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
  File "/home/bishr/.local/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 342, in instantiate_node
    value = instantiate_node(
  File "/home/bishr/.local/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 333, in instantiate_node
    _target_ = _resolve_target(node.get(_Keys.TARGET), full_key)
  File "/home/bishr/.local/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 139, in _resolve_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error locating target 'src.models.components.uedm.UEDM', set env var HYDRA_FULL_ERROR=1 to see chained exception.

**Comment by XavierJiezou** [comment]
This bug was caused by the name change of our model (UEDM → CMFNet), which has been fixed. You can try cloning the code again.
